### ISSUE TITLE
absolute layout within absolute layout

### ISSUE THREAD

**Issue by victordiaz** [Protocoder/Protocoder#61]
add an absolute layout that can be repositioned within the default absolute layout

**Comment by guyikcgg** [comment]
Is `absolutelayout.addView(view, x, y, w, h)` working properly?
I get this error: `org.mozilla.javascript.EcmaError: ReferenceError: "absolutelayout" is not defined.`

**Comment by guyikcgg** [comment]
Use `ui.addAbsoluteLayout` To add a an absolute layout, then you can add some views. Here a view seems to be button, a label, etc.
